INSERT INTO literature_questions (
    question_code, 
    question, 
    correct_answer, 
    incorrect_answer1, 
    incorrect_answer2, 
    incorrect_answer3, 
    answer_notes, 
    created_at
) VALUES 
('L05_01', 
'Texto dramatico surgido en grecia donde el personaje pertenece a la nobleza y el dolor sobrepasa al protagonista.', 
'Tragedia', 
'Comedia', 
'Drama', 
'Tragicomedia', 
'', 
NOW()),

('L05_02', 
'Son caracteristicas del modernismo:', 
'Musicalidad, lo estetico y la subjetividad', 
'Realismo, objetividad, precisión', 
'Utilitarismo, pragmatismo, racionalidad', 
'Imaginación, excesiva descripción', 
'', 
NOW()),

('L05_03', 
'Son obras del modernismo:', 
'Azul, cantos de vida y esperanza', 
'Don Quijote de la Mancha', 
'La Odisea', 
'Fervor de Buenos Aires', 
'', 
NOW()),

('L05_04', 
'Son obras del romanticismo:', 
'Rimas y leyendas', 
'El retrato de Dorian Gray', 
'Madame Bovary', 
'Las flores del mal', 
'', 
NOW()),

('L05_05', 
'Variante del realismo que describe y analiza la realidad sordida, cruda y miserable del hombre', 
'Naturalismo', 
'Realismo', 
'Idealismo', 
'Romanticismo', 
'', 
NOW()),

('L05_06', 
'Corriente artistica de la primera mitad del siglo XIX, su postulado es la libertad', 
'Romanticismo', 
'Barroco', 
'Renacimiento', 
'Realismo', 
'', 
NOW()),

('L05_07', 
'Caracteristicas de las tragedias', 
'Final funesto, los heroes son pedestinados y reflejan los valores de la epoca', 
'Final feliz, los heroes alcanzan la redención', 
'Personajes superficiales y de baja moralidad', 
'Los personajes son generalmente invisibles', 
'', 
NOW()),

('L05_08', 
'El poema del Mio Cid pertenece al genero:', 
'Narrativo', 
'Poético', 
'Dramático', 
'Ensayo', 
'', 
NOW()),

('L05_09', 
'La _________ es una caracteristica del texto poetico.', 
'Polisemia', 
'Anáfora', 
'Metonimia', 
'Ironía', 
'', 
NOW()),

('L05_10', 
'Don quijote de la mancha pertenece al genero:', 
'Epico', 
'Drama', 
'Novela corta', 
'Lírica', 
'', 
NOW());
