@api = http://localhost:3000/tasks

GET {{api}}

###
GET {{api}}/1
###

GET {{api}}/count

###
POST {{api}} 
Content-Type: application/json
Content-Length: 54

{
    "title": "third task",
    "description": "some description task"
}